name: Build and Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      
      - name: Install UCC
        run: pip install splunk-add-on-ucc-framework
      
      - name: Build
        run: ucc-gen build --source alert_apprise/package --ta-version ${{ env.TAG_NAME }}
      
      - name: Package
        run: ucc-gen package --path output/alert_apprise
      
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: alert_apprise-${{ env.TAG_NAME }}.tar.gz
      
      - name: Publish to Splunkbase
        run: |
          ucc-gen publish \
            --package-path alert_apprise-${{ env.TAG_NAME }}.tar.gz \
            --username ${{ secrets.SPLUNKBASE_USERNAME }} \
            --password "${{ secrets.SPLUNKBASE_PASSWORD }}" \
            --app-id ${{ vars.SPLUNKBASE_APP_ID }} \
            --splunk-versions ${{ vars.SPLUNK_VERSIONS }} \
            --cim-versions ${{ vars.CIM_VERSIONS }}